name: Github Pages

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #- name: Some introspection
      #  run: echo PATH=$PATH HOME=$HOME GITHUB_WORKSPACE=$GITHUB_WORKSPACE PWD=$PWD ;
      #       pwd ; ls -l ; make -v

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
          dest: '"${HOME}/racketdist"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never

      - name: Package Installation
        run: raco pkg install --auto --update-deps --installation commonmark

      - name: Build the site
        # Somehow(!) `make public` fails with GitHub's GNU Make 4.3 complaining:
        # make: *** No rule to make target 'public/index.html', needed by 'public'.  Stop.
        run: make gh-pages

      - name: Push to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
